### ISSUE TITLE
Go-amd64: map intptr_t and uintptr_t to Go's equivalents

### ISSUE THREAD

**Issue by robskie** [Maratyszcza/PeachPy#22]
The generator outputs an error for functions with signed/unsigned_int argument. Here's the last few lines of the error:
```
File "/Library/Python/2.7/site-packages/peachpy/x86_64/function.py", line 987, in __init__
    self.go_signature = function.go_signature
  File "/Library/Python/2.7/site-packages/peachpy/x86_64/function.py", line 158, in go_signature
    go_argument_types = list(map(c_to_go_type, map(operator.attrgetter("ctype"), self.arguments)))
  File "/Library/Python/2.7/site-packages/peachpy/x86_64/function.py", line 149, in c_to_go_type
    }[ctype.size]
KeyError: None
```
It also outputs an error when the return type is signed/unsigned_int. Right now I'm substituting int64_t/uint64_t for signed/unsigned_int and just change the function signature to use int/uint since int and uint type in go is actually represented as 64-bit in amd64 as stated [here] (https://golang.org/doc/go1.1#int). It would also be nice if Go's uintptr can also be supported.

**Comment by Maratyszcza** [comment]
This is deliberate, albeit the error message could be better.
The types specified for `Argument` objects and `Functions`'s `result_type` are C types, not Go types. The C's `int` type is very different from Go's `int` type, which is why PeachPy doesn't map one to the other.

The C type that maps to Go's `int` is `ptrdiff_t`, and the C type that maps to Go's `uint` is `size_t`.

**Comment by robskie** [comment]
I would suggest creating another type like `int_t` or `uint_t` with the same type definition as `ptrdiff_t` and `size_t` so that it's easier to remember.

Anyway, I still can't use `ptrdiff_t` and `size_t` as the function's result type. Here's my test code:

```python
with Function('test_func', (), ptrdiff_t:
    RETURN(rax)
```

And here's the error:

```
File "/Library/Python/2.7/site-packages/peachpy/x86_64/pseudo.py", line 178, in __init__
    format(str(self.operands[0]), str(active_function.result_type)))
ValueError: Register rax can not be converted to return type ptrdiff_t
```

**Comment by Maratyszcza** [comment]
The `Function` object in PeachPy is ABI-independent: it is possible to generate output for different ABIs from the same assembly source without re-parsing it. Thus, PeachPy complains that `rax` does not fit into `ptrdiff_t`, because on some ABIs (e.g. Linux x32 ABI and Golang's amd64p32) it doesn't.

**Comment by robskie** [comment]
I think the `Function` object should check if the given ABI supports 32 or 64 bit pointers before deciding if a register fits into `ptrdiff_t` or `size_t`.

**Comment by Maratyszcza** [comment]
Probably you use command-line interface and don't see these details, but on Python interface level `Function` object doesn't know the target ABI. ABI is specified later, when the function is finalized, and finalizing the function multiple times for different ABIs is a supported and important use-case, e.g.
```
with Function(...) as generic_function:
    ...

system_v_x86_64_function = generic_function.finalize(abi.system_v_x86_64_abi)
linux_x32_function = generic_function.finalize(abi.linux_x32_abi)
```

**Comment by robskie** [comment]
Ah, ok. I get it now. Thanks for the clarification.
