### ISSUE TITLE
Example does not work on Linux amd64

### ISSUE THREAD

**Issue by deepankarsharma** [Maratyszcza/PeachPy#38]
Get this error ->
python -m peachpy.x86_64 -mabi=sysv -mimage-format=elf -o matmul.o matmul-opt.py 
/usr/bin/python: No module named avx; 'peachpy.x86_64' is a package and cannot be directly executed

Also running make gives this ->
user@ne:~/Downloads/PeachPy-master/examples/make$ make
python -m peachpy.x86_64 -MMD -MF matmul-opt.d -o matmul-opt.o matmul-opt.py
/usr/bin/python: No module named avx; 'peachpy.x86_64' is a package and cannot be directly executed
Makefile:12: recipe for target 'matmul-opt.o' failed
make: *** [matmul-opt.o] Error 1

This is on ubuntu wily with built in Python 2.7.10.

**Comment by Maratyszcza** [comment]
It seems that you didn't generate the instruction classes. See [installation instructions](https://github.com/Maratyszcza/PeachPy#installation)

**Comment by deepankarsharma** [comment]
User error :) Example works once I followed the instructions.

**Comment by Maratyszcza** [comment]
Thank, I close the issue then

**Comment by pwaller** [comment]
I just hit this. This is not user friendly. Is there a good reason to break `pip install git+https://github.com/Maratyszcza/PeachPy`? If I want to tell a user or developer to install peachpy so that they can build things I write, I would hope peachpy is really be as simple as possible to install (and follow the standard way all other python modules are built). Telling the users they have to come and read your README before they can get started with mine is not ideal. I don't want to write the installation instructions for peachpy in my README either, because they might go out of date in time.

**Comment by Maratyszcza** [comment]
@pwaller I'm not an expert on Python packing, but it seems that you are. If you could fix it and submit a PR, it would be a welcome contribution!

**Comment by pwaller** [comment]
In case anyone is reading this, it was resolved in #61.
